### ISSUE TITLE
Remove auto id from svg-image

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#10]
I hate how Illustrator gives all the SVGs id="Layer-1", can we make it so the component doesn't put an ID on the SVG unless it is set manually? Or should we just remove the id if it's `Layer-*`?

**Comment by SaFrMo** [comment]
I usually go in and edit the SVG file itself, which I think is safer than having svg-image do any SVG modification on the fly. This is all you need for a bare-bones working SVG, so anything extra can be deleted:

```html
<svg
    xmlns="http://www.w3.org/2000/svg" <!-- required svg namespace -->
    viewBox="0 0 100 100" <!-- coordinate system - see below -->
    >

    <!-- paths, polygons, shapes, etc. can go in here - it's often helpful to group them using group <g> tags, but not necessary -->

</svg>
```

[Here](https://www.sarasoueidan.com/blog/svg-coordinate-systems/) is a great reference on the viewBox coordinate system. No `<title>`, no `id`s or `data-name`s, no inline styling declarations (if anything, use more easily-overridden attributes like `width="50" fill="#fff"` etc.) needed. Editing the SVG itself should solve any problems you'd want to solve in `svg-image` - let's talk more if it doesn't!

**Comment by drewbaker** [comment]
OK, I'll do it manually. But it's just a pain in the ass, and for sure is going to fall threw the cracks. It doesn't really matter having a bunch of `Layer-1` ids on SVGs anyway.

**Comment by SaFrMo** [comment]
Agreed about it being a pain!
