### ISSUE TITLE
Make video-stage work with YouTube

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#102]

**Comment by johndigital** [comment]
This is a little trickier than I expected. The way it works with Vimeo right now is to just use the public Vimeo oembed endpoint to fetch the iFrame code. I tried to do the same with YT but it's apparently not something they support.

The oembed endpoint they provide works great if you go directly to it, [example](https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=wnF-zTrHvGs). But it has no CORS headers so it can't be called directly from the browser. The only way around this in the browser is to import a big youtube specific SDK.

So I think the options here would be:
1. Build an endpoint into WordPress using the VuePress theme to accept any URL and run it through [wp_oembed_get](https://codex.wordpress.org/Function_Reference/wp_oembed_get) and return the HTML. Then use that endpoint for all embeds that video-stage does. The downside of this would be that it couples video-stage really tightly to VuePress but it would work well.
1. Do that same idea, but with a generic service like [NoEmbed](https://noembed.com/) so it's not coupled with VuePress. Or host our own version of that service and use that. Downside of course is that if it ever goes down it would impact a lot of sites.
1. Decide we don't care about the extra overhead and just include the youtube SDK to get the oembed code.

Thoughts @drewbaker or @SaFrMo ? I think option #1 would be my preferred.

**Comment by drewbaker** [comment]
Spoke with John about this. Will be much easier to just use WordPress to fetch the oembed and return the iframe as a meta string.
