### ISSUE TITLE
Menu item classes and URLs wrong

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#12]
Guys, the classes given to menu items are wrong. Sometimes you get two `router-link-active` and it seems categories get `current-menu-ancestor` always...

![screen shot 2017-12-09 at 9 12 55 pm](https://user-images.githubusercontent.com/475015/33802188-fe232504-dd25-11e7-909f-e68211ecb749.png)

**Comment by drewbaker** [comment]
Actually, I think categories don't seem to work at all. The URL just ends up being the home page...

**Comment by drewbaker** [comment]
Maybe this helps. I have a menu on the category pages that is all the other categories. The names are right, but the classes are all wrong, and one of them gets the href `/4/2-revision-v1`.

**Comment by johndigital** [comment]
This should now be solved in the newest version of rest-easy. The classes I believe were a side-effect of the incorrect URLs
