### ISSUE TITLE
Build a proper slideshow component

### ISSUE THREAD

**Issue by johndigital** [funkhaus/fh-components#16]
Using "scoped slots" is the way to do this: https://vuejs.org/v2/guide/components.html#Scoped-Slots

Add some documentation about gallery gravity effects, and add minimum styling.

**Comment by SaFrMo** [comment]
I started a branch called slideshow to work on this. Looks like Vue testing [might not support scoped slots](https://github.com/vuejs/vue-test-utils/issues/156) yet, so that's something to keep in mind!

**Comment by SaFrMo** [comment]
From Drew's wishlist at #22:

> OK, here is my running list of things that are common for slideshows/galleries

- [X] Work as a component or as a shortcode in wp-content
- [X] Next/Prev divs
- [X] Pagination indicator (either boxes or numbers)
- [X] Video background, or image background
- [X] Gravity on contents (probably just use CCS classes)
- [X] Auto advance of slides
- [X] Option to stop auto advance on click
- [X] Ability to start at X index slide
- [X] Ability to jump to X index slide
- [X] Delay start of slide by X seconds (useful when showing multiple galleys on a page in a grid)
- [X] Basic events (maybe not needed yet)
- [X] Basic methods (maybe not needed yet)

**Comment by johndigital** [comment]
Version 1 of this is now implemented and documented in https://github.com/funkhaus/fh-components/commit/ba0ff2eeaa8b14b3493b605394e5beb9ac401913. All of the above features are included!
