### ISSUE TITLE
Build tests for existing components

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/fh-components#19]
- [ ] flex-text
- [x] hamburger-button
- [x] split-text
- [ ] transition-fade
- [x] v-full-height
- [ ] video-stage
- [ ] wp-content
- [ ] wp-menu
- [ ] wp-menu-item
- [ ] slide-show

@drewbaker @lwaldner Whenever you get a free moment, could you take a look at the [tests docs](https://github.com/funkhaus/fh-components#tests) and make sure everything makes sense? 

It might be good to write some tests for a component or two as well to try it out, and we should also get in the habit of adding new tests when we add new features. Thanks!

**Comment by drewbaker** [comment]
Looks good to me. I don't know much about `tap`, why did you pick that one?

**Comment by johndigital** [comment]
@drewbaker Tap is the protocol that heroku wants you to use when you [write tests for their CI](https://devcenter.heroku.com/articles/heroku-ci). Can't imagine we'd ever use the Heroku CI for fh-components, but tap is just what I'm used to working with from Sayso etc.

Mocha is more popular, so maybe we should use that? But it probably doesn't matter.

**Comment by drewbaker** [comment]
Yeah I’ve heard of Mocha. But if Heroku use it then that’s a big plus for me. I can see us being familiar with that only helping in the future. Plus I like taps whole “should work like a normal function” approach.

**Comment by johndigital** [comment]
@drewbaker Actually, now that I'm looking into this a little deeper it looks like tap is just one of many formats that any test tool will output results in, and you don't have to use a specific package.

You can tell mocha to output in tap format for instance. I'll make a new issue for myself to look into this more, because it might make more sense for use to learn mocha since it's the standard.

**Comment by SaFrMo** [comment]
Marking hamburger as complete - nothing to test programmatically

**Comment by SaFrMo** [comment]
Ditto for v-full-height

**Comment by SaFrMo** [comment]
@johndigital @drewbaker Any objection to closing this issue? It's a good idea but not one we've been keeping up on, and lots of these components are browser-dependent. Thoughts?

**Comment by drewbaker** [comment]
Yeah not a huge priority right now.
