### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/fh-components#2]
- [X] Video detail page (probably more like video-stage with pagination and Vimeo events working)
- [x] Hamburger menu that emits clicked events (be aware of sub-menus too). Should have click blocker awareness too. 
- [X] `stage` that you can drop in a video detail page
- [x] A menu panel (slide over, push out, from top/left/right)
- [X] Add html video capability to `responsive-image` component
- [X] Add slot to responsive-image component
- [X] Social links

**Comment by drewbaker** [comment]
For the pure `<img>` tag, if we use this: https://developer.wordpress.org/reference/functions/wp_get_attachment_image_srcset/ then we should be able to include the src set in the JSON that comes out of reset easy, and have a <image> component that gets built off the attachment object.

**Comment by drewbaker** [comment]
Just went over `responsive-image` with Sander. I think it would be great to add some parameters to it to allow for no wrapping DIVs. Maybe like:

```<responsive-image :object="companyThumbnail(company)" size="medium-thumb" not-wrapped/>```

If it's possible to not have any wrapping, but still have it work with Funkycolor etc, that would be sweet. The reason being, I have a forced 16:9 grid, so I don't need all the wrapping DIVs that `responsive-image` has by default.

**Comment by drewbaker** [comment]
Allow `responsive-image` to have a slot, that puts content as a sibling to the `<img>`, like so:

```
                <responsive-image :object="thumbnail(object)" size="medium">
                    Something in here
                </responsive-image>
```

**Comment by johndigital** [comment]
@drewbaker I just pushed an upgrade that adds some new functionality to `responsive-image` (1.2.13). 

The slot you suggested is now implemented (very handy suggestion), `fill-space` is working as expected and handles background colors nicely, and images never get put in the loading state if they are loaded out of the browser's cache.

**Comment by drewbaker** [comment]
Any video player/stage that we build needs to auto play videos muted.

**Comment by drewbaker** [comment]
Guys, here is my attempt at a bare bones video detail page. It uses FitToParent and has the Vimeo API on it. We should probably expand this into using the ended event, and have some pagination on it perhaps (or save that for vuepress, and trim this down to just the stage and make it a component).

```
<template>
    <main class="content video-detail">

        <div class="video-player">
            <div class="stage" v-html="iframeEmbed"></div>
        </div>

    </main>
</template>

<script>
    import fitToParent from 'fit-to-parent'
    import Player from '@vimeo/player'
    import _get from 'lodash/get'
    import Vue from 'vue'

    export default {
        computed: {
            iframeEmbed() {
                return _get(this.$store.state.loop[0], 'meta.custom_video_url_embed', '')
            }
        },
        watch: {
            iframeEmbed () {
                this.playIframe()
                Vue.nextTick(this.sizeVideo)
            }
        },
        mounted() {
            // Size video right away
            this.sizeVideo()

            // start iframe if possible
            this.playIframe()

            // Size video on window resize
            this.$root.$on('throttled.resize', this.sizeVideo)
        },
        beforeDestroy () {
            this.$root.$off('throttled.resize', this.sizeVideo)
        },
        methods: {
            getIframe () {
                return this.$el && this.$el.querySelector('.stage iframe')
            },
            playIframe () {
                if ( !this.getIframe() ) return
                const player = new Player(this.getIframe())
                player.play().catch(err => player.unload())
                player.on('ended', () => {
                    alert('It ended!')
                })
            },
            sizeVideo () {
                if ( this.getIframe() ) {
                    fitToParent({
                        element: this.getIframe(),
                        heightOffset: 0
                    })
                }
            }
        }
    }
</script>

<style lang="scss">
    .video-player {
        background-color: #000000;
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;

        .stage {
            position: absolute;
            top: 50px;
            left: 50px;
            right: 50px;
            bottom: 50px;
            box-sizing: border-box;
            display: flex;

            iframe {
                margin: auto;
            }
        }
    }
</style>
```

**Comment by johndigital** [comment]
@drewbaker this looks really good! My vote is to take the fitToParent and vimeo API pieces out of this and abstract them into a `<stage>` component like you mentioned. Then we could use props and events to control the behavior and it would be really clean. Something that could maybe be used like this:

`<video-stage :embed="iframeEmbed" autoplay="true" @end="goToNext" />`

**Comment by drewbaker** [comment]
Yeah that seems like the move. Can you do that?

We could style that at the parent level.

**Comment by johndigital** [comment]
I've removed "svg component that doesn't get wrapped..." from the list. This is no longer possible and probably just a bad idea now that `svg-image` supports absolute URLs as described in https://github.com/funkhaus/fh-components/issues/31

I've also marked off Social Links, as those should now be easily handled with the wp-menu templating feature added in https://github.com/funkhaus/fh-components/commit/ca6fb69b4ad175b2308919a3e4fcfd01fbccc414

**Comment by johndigital** [comment]
I'm not sure I understand the use case for the "Pure img Element..." in this list. Any insight @drewbaker @SaFrMo  ?

**Comment by drewbaker** [comment]
I’m not going to fight for it anymore, but I really wish we didn’t have to wrap SVGs in divs always. 

Not sure on that pure image thing? Maybe that was due to not being able to use SVGs that weren’t in the theme folder?

**Comment by johndigital** [comment]
Okay, I'm going to just go ahead and remove it then because I'm not sure why we'd need it

**Comment by SaFrMo** [comment]
Closing this issue since all items are checked off!
