### ISSUE TITLE
Slideshow gallery wishlist

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#22]
OK, here is my running list of things that are common for slideshows/galleries

- [ ] Work as a component or as a shortcode in wp-content
- [ ] Next/Prev divs
- [ ] Pagination indicator (either boxes or numbers)
- [ ] Video background, or image background
- [ ] Gravity on contents (probably just use CCS classes)
- [ ] Auto advance of slides
- [ ] Option to stop auto advance on click
- [ ] Ability to start at X index slide
- [ ] Ability to jump to X index slide
- [ ] Delay start of slide by X seconds (useful when showing multiple galleys on a page in a grid)
- [ ] Basic events (maybe not needed yet)
- [ ] Basic methods (maybe not needed yet)

**Comment by SaFrMo** [comment]
Closing this to keep conversation in #16
