### ISSUE TITLE
Reverse hover

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/fh-components#23]
We end up needing to do a reverse-hover effect a good bit, so I'd like to make an fh-component to handle this. I was thinking a directive on the wrapper element - something like:

```
<nav class="menu" v-reverse-hover>
    <router-link v-for="item in menuItems" :to="item.relativePath">{{ item.title }}</router-link>
</nav>
```

Is this a good use of a directive, @jrobson153 @drewbaker @lwaldner , or is there another way you'd do it?

**Comment by drewbaker** [comment]
When you say "reverse hover", do you mean basically adding a "not-hovered" class on all other items when something else is hovered on?

**Comment by SaFrMo** [comment]
Yep! That's what I was thinking.

**Comment by SaFrMo** [comment]
@drewbaker Just talked this through with @jrobson153 a bit and there's no clear solution jumping out to us. I might make this a prop on the `wp-menu` component for the time being - that's where we use it the most and it'd be pretty easy to implement there.

I'd like a wrapper directive or element like the first comment above, but that feels like it should react to dynamic child links, and I'm not sure if that'd do the job. I'll look into it when I have some more time!

**Comment by SaFrMo** [comment]
Added in 210efb5! See the [documentation](https://github.com/funkhaus/fh-components#reverse-hover) for more info.
