### ISSUE TITLE
FitVids for iFrame embeds in wp-content

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#25]
Would be great if `wp-content` also did something like FitVids for a whitelisted set of iFrame.

**Comment by drewbaker** [comment]
Also, whatever Vue version of unwrap `.entry > p > img.alignnone` would be helpful!

**Comment by SaFrMo** [comment]
See [CapGun](https://github.com/funkhaus/capguncollective.com/blob/master/src/views/Default.vue) for a good implementation of this. I'll add it in later on today!

**Comment by SaFrMo** [comment]
Added in c8fc8bf.
