### ISSUE TITLE
svg-image click events

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#3]
Currently with SVG images, to get click events to work I have to do this:
`<svg-image class="close" src='close-x.svg' v-on:click.native="scrollUp"></svg-image>`

Not sure the `click.native` is the best way to do that, but it's the only way I got it working.

I also hate that the SVG gets wrapped in a DIV.

**Comment by johndigital** [comment]
The way you've done it is the correct way. The `.native` operator serves as a separation between  events that are fired on the component itself vs events fired on the root DOM element of the component. This doesn't have much to do with our SVG component, it is a common pattern you'll need to use in many places. Going to close this issue for now, feel free to re-open if you think there's still a problem!
