### ISSUE TITLE
svg-image absolute URL support

### ISSUE THREAD

**Issue by johndigital** [funkhaus/fh-components#31]
If a full URL is passed in to the `src` prop, and the URL has a .svg extension, the component should attempt to fetch the SVG code with AJAX and load its contents that way. 

Note that it's VERY important to do as much validation as possible that the response you get is actually an SVG, because it will get injected into the page as HTML.

**Comment by drewbaker** [comment]
Good idea. Should it just display it as an IMG first, then go do the Ajax request? Basically this is the same as the way we’ve done it with jQuery for years and it seemed to work great.

**Comment by johndigital** [comment]
@drewbaker yea, that's a good call. If an absolute URL is passed in, it will render an img tag until the ajax response comes back.

**Comment by johndigital** [comment]
This is now implemented in https://github.com/funkhaus/vuepress/commit/8e4a0abada9dedcf913d6b5e5d935f66eda6ebc2
