### ISSUE TITLE
Mailchimp component

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/fh-components#32]
- [ ] Mailchimp ID
- [ ] Signup message + cancel button + submit button
- [ ] Slot(s)
- [ ] Thank You message

(add others as needed)

**Comment by drewbaker** [comment]
Might be better to not make this an overlay, because it would be better if it was easy to add the `<mailing-list>` component inside anything really.

**Comment by SaFrMo** [comment]
Agreed! Edited the original list.

**Comment by johndigital** [comment]
Built out first version of this with support for both mailchimp and madmimi: 27fcaa9a5f19af136a6152b27b5a775ad56a9a0c

Still need to add documentation, so leaving this issue open

**Comment by SaFrMo** [comment]
Added documentation to 225783b. Closing!
