### ISSUE TITLE
Allow script tags in wp-content

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/fh-components#33]
Prevent this Vue error somehow:

```
- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.
```

**Comment by drewbaker** [comment]
Why do we need script tags in wp-content?

**Comment by SaFrMo** [comment]
I copied the embed code from a tweet and it came with a script tag - didn't want us to run into the problem unexpectedly down the road.

**Comment by drewbaker** [comment]
The right way to do that would be a URL as an oEmbed... but it might just put a script tag in anyway.

**Comment by johndigital** [comment]
This is a tricky one. We definitely will want clients to be able to just drop the twitter embed code into the content editor and have it work as expected. Not sure if there will be a good workaround, it makes sense that vue doesn't want you putting script tags in there.

**Comment by SaFrMo** [comment]
Haven't run into this in any major way since raising the issue, so I'm going to close!
