### ISSUE TITLE
Allow content inside of slide-show component 

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#39]
I'd like to be able to add markup to the bottom of a slideshow. This is common for things like scroll down prompts and page titles, or perhaps an excerpt. Something like this:

```
    <slide-show class="slideshow" :slides="slides" :loop="false" :infinite="false" :index.sync="slideIndex">

        <div class="slide" slot="slide" slot-scope="{ slide }">
            <responsive-image :object="slideImage(slide)" size="fullscreen" :fill-space="true"/>
        </div>

        <svg-image slot="nav-prev" src="arrow-left.svg"/>
        <svg-image slot="nav-next" src="arrow-right.svg"/>
        <svg-image class="scroll-down" src="arrow-down.svg"/> <!-- This thing doesn't work -->
    </slide-show>
```

**Comment by SaFrMo** [comment]
Looks like this is already implemented [here](https://github.com/funkhaus/fh-components/blob/master/src/slide-show/SlideShow.vue#L53) - feel free to reopen if it's not working for some reason, but I tested and it looks good!
