### ISSUE TITLE
Add .not-hovered and .is-hovered classes on menu items

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#4]
A very common use case for menus is to have the current menu item set to `opacity: 1` and all other menu items set to `opacity: 0.X`. The only way to do this reliably is to add classes to the menu items, using pure CSS is never accurate enough.

So can the menu component add `.not-hovered` and `.is-hovered` to all menu items?

**Comment by SaFrMo** [comment]
Accidentally duplicated this in #23 - closing this issue since most of the conversation exists there now.
