### ISSUE TITLE
Add index as parameter on slot-scope of slide-show

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#40]
I want to be able to do this `{ slide, index }`. Like below:

```
    <slide-show class="slideshow" :slides="slides" :loop="false" :infinite="false">

        <div class="slide" slot="slide" slot-scope="{ slide, index }">
        </div>

    </slide-show>
```

**Comment by SaFrMo** [comment]
Looks like this is already implemented: https://github.com/funkhaus/fh-components/blob/master/src/slide-show/SlideShow.vue#L23

Feel free to reopen if there's an issue!
