### ISSUE TITLE
Emit events from in-view directive

### ISSUE THREAD

**Issue by johndigital** [funkhaus/fh-components#43]
I'm not sure if this is even a good idea, but I think it would be pretty useful to have events come off of the `in-view` directive so you could for instance run a full js animation when the element comes in or out of view.

Seems like technically it might be possible, since the [binding](https://vuejs.org/v2/guide/custom-directive.html#Directive-Hook-Arguments) gives you access to the VNode object. Maybe you could use the $emit method from there?

What do you think @SaFrMo ?

Actually now I'm thinking about it, it would probably be more "vue-friendly" to pass a handler method to the value of the directive instead and then the directive would be responsible for triggering it at the right time.

**Comment by SaFrMo** [comment]
> pass a handler method to the value of the directive instead and then the directive would be responsible for triggering it at the right time.

I think that's how I'd do it - something like:

```html
<responsive-image v-in-view="{ onEnter, onLeave }"/>
```

and then in the `export` define `onEnter` and `onLeave`.

I think it'll start to feel more like a wrapper component than a directive if we go any farther than this, but I definitely like the idea of `v-in-view` giving you some lower-level access to its methods!

**Comment by SaFrMo** [comment]
Added to 1693425!
