### ISSUE TITLE
Use AI to for image alt attr for responsive images if no alt text provided

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#48]
One of the main issues with accessibility reviews is that images aren't provided alt text. Obviously this is a content issue mostly, so it would be awesome if we could provide some sort of fallback if a human didn't enter alt text. I imagine it would work similar to funky-colors, so perhaps its not really a fh-components issue but I thought I'd open it here for us to discuss.

**Comment by lwaldner** [comment]
@drewbaker So are you thinking some sort of image recognition? We upload a image to wordpress and it generates a string of objects in the image?

**Comment by drewbaker** [comment]
Yeah exactly. Hopefully better than just “sandwich, knife, table” and more like “knife cutting a sandwich on a table”.

**Comment by lwaldner** [comment]
Yeah this is 100% do-able. Transforming the list of predicted objects in the image into a coherent sentence may be difficult but i'll do some research.

**Comment by lwaldner** [comment]
@drewbaker looks like we would have to implement this in order to get alt text like you were suggesting.

https://arxiv.org/pdf/1612.04520.pdf

My thinking is get a simple image recognition system running on a lambda instance or something then move onto implementing this paper

**Comment by lwaldner** [comment]
Did a little more digging and found the seminal paper on image caption generation. So ignore the action classification paper lol. 

http://proceedings.mlr.press/v37/xuc15.pdf

**Comment by drewbaker** [comment]
The more I think about this, the more it should be a part of Funky colors. Seems like we should probably rename that plugin and just have it do a bunch of advanced image meta data work. Colors, alt tags... I wonder if there is anything else we can do for it? Emotion cataloging? 

I wonder if we make it a proper WordPress plugin and have it have a paid tier?

**Comment by SaFrMo** [comment]
Closing this issue for now since we're working on the plugin elsewhere and it's outside the scope of fh-components!
