### ISSUE TITLE
Add class to the media in responsive image

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#49]
If it's easy to do, it would be handy to have the image and video elements inside a responsive image to get given a class. I was thinking `.media`?

Because if you want to do a zoom hover effect, currently you need to do this:

```
.block:hover {
    .image-sizer > * {
        transform: scale(2);
    }
}
```

I don't know if this is a valid fear, but I try to avoid `> *` when possible. Would be good to have:

```
.block:hover {
    .image-sizer .media {
        transform: scale(2);
    }
}
```

**Comment by johndigital** [comment]
That's a really good point, I end up doing that a lot as well. I'll assign this to myself and add it in.

**Comment by johndigital** [comment]
Added in 0b56896905cc9946ec0935f89453c00a8e291860
