### ISSUE TITLE
Add ids and classes on wp-menu items 

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#53]
Current version of wp-menu has no classes or ids on the menu `<li>`. Would be great to get as many of the default WordPress ids and classes as possible, and hopefully some other useful ones like: `.menu-item-is-home-page` or `.menu-item-{dev_id}`

**Comment by drewbaker** [comment]
![screen shot 2018-04-11 at 1 24 05 pm](https://user-images.githubusercontent.com/475015/38641370-a595d2c6-3d8b-11e8-9b91-3cc199e92679.png)

Reference of what the default WordPress ids and classes look like.

**Comment by johndigital** [comment]
@drewbaker this is now set up, but it takes a few different pieces to get all the features you want. Here are the details:

1. If you just `npm update fh-components` you will get a lot of classes that you didn't have before; nav ID, page ancestor, etc.
2. If you install the latest Rest Easy, you will also get a class telling you which of the nav items is set as "Home" (the page_for_posts setting)
3. After doing both of those, if you add [this filter](https://github.com/funkhaus/vuepress/blob/master/functions/rest-easy-filters.php#L13-L28) (which is now in vuepress by default) to your `rest-easy-filters.php` file you will also get a class giving you the Dev ID of each page item

**Comment by drewbaker** [comment]
John, do you think we could preface these classes with `menu-item-`? Just seems a little top level to have `dev-id-news` class in the menu, everything else is prefaced. Am I overthinking this?

**Comment by johndigital** [comment]
You might be overthinking it! But that's okay, I'll change it out so they're all consistent haha

**Comment by johndigital** [comment]
Fixed in 02808ad049d2290fdca74b44c8e46b6e1b35091e
