### ISSUE TITLE
Add sound toggle to responsive-image

### ISSUE THREAD

**Issue by johndigital** [funkhaus/fh-components#54]
Kids at Play has a full screen video on a page being powered by responsive-image and they would like to be able to turn sound on/off (I have run into this on a different site as well.)

So, to make this work we have 2 options as far as I can tell:
1. Set up slots for "sound-on" and "sound-off", allowing the developer to feed in the template for whatever icon/markup they want to control each state. Responsive image would handle all the logic, so this would function similar to how prev and next arrows in slide-show work currently
2. Just add a "muted" prop that is true by default, and whenever one of use needs to use it we just build out the icons using the main `<slot>` in responsive image and build the logic ourselves.

Now that I've written it out, I'm definitely leaning towards option 2 because if we go with 1 we'll have to make a lot of assumptions about the UI.

Thoughts before I build this @SaFrMo @drewbaker @lwaldner ?

**Comment by drewbaker** [comment]
Yeah I think it has to be #2. Muted prop makes the most sense. I think it should default to muted too. 

A lot of the time I’d want the mute button to be not inside the responsive image too, so having the prop makes the most sense.

**Comment by johndigital** [comment]
Okay perfect, going to add this today.

**Comment by johndigital** [comment]
Added and documented! 150d8ed67a327f83359cbaf7fb4c96f74427759f

Instead of `muted` I decided to do `volume` (between 0 and 1) to give us a little more control if we need it. The default is 0, and whenever set to 0 the video element will have the `muted` attribute so it will still be able to autoplay in Safari.
