### ISSUE TITLE
Add swipe functionality to slide-show by default

### ISSUE THREAD

**Issue by johndigital** [funkhaus/fh-components#57]
This will require a dependency on Hammer.js

**Comment by drewbaker** [comment]
If you don’t want to use hammer, this is how jQuery does it under the hood. Think we could just port this to straight JS?

http://malsup.github.io/jquery.cycle2.swipe.js

**Comment by johndigital** [comment]
Added and documented in b3c4139b72808e23e40fdd9db1e37064e12e8a90

Just used hammer for now, but we may want to explore something lighter in the future. Surprisingly I could not find any tiny libraries that just detect swipe. Porting the Cycle code to vanilla js would be a good solution, but will take some time.
