### ISSUE TITLE
v-reverse-hover string selector doesn't work

### ISSUE THREAD

**Issue by johndigital** [funkhaus/fh-components#58]
When trying to use this directive, it seems to work with an array of selectors but not with a single string selector like the documentation says. Example:

This works:
`v-reverse-hover="{ selectors: ['.grid-row a'] }"`

This does not work:
`v-reverse-hover="{ selectors: '.grid-row a' }"`

**Comment by SaFrMo** [comment]
Fixed in 0facfa9!
