### ISSUE TITLE
A component that loads data on when it becomes in view

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#60]
John and I were talking about how an infinite scroll component could be built, and still be modular. This is what we came up with. Basically it just loads a URL when it comes in view, and then it's up to the developer to do something with that data (essentially just update $store.loop in a Vue friendly way).

```
        <load-on-view 
            :next-url="$store.meta.paged+1" 
            @data="callback" 
            @finish="otherCallback"
        />
```

**Comment by johndigital** [comment]
Going to build this for Jane

**Comment by johndigital** [comment]
Built and documented in d7d715efc2d698ae51011576853b214b975bed82 !

**Comment by drewbaker** [comment]
So sick! Good work John.

One idea for future. Add a prop called `offset` that will basically activate before it comes into the view port bu the `offset` amount.
