### ISSUE TITLE
responsive-image on IE not working... obviously  

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#69]
So I have an `object-fit: cover` responsive image on Bernards. `object-fit` doesn't work on IE, so the image gets stretched and looks horrible. Ordinary I'd just say "Don't use IE" but of course this client's entire 200+ person office is using it!

Maybe we add this? https://www.npmjs.com/package/object-fit-polyfill 

Or just change it for this one website only perhaps?

![ie_object_fit](https://user-images.githubusercontent.com/475015/40570488-5c6b5904-6040-11e8-8a7d-0c0223ff3cd0.jpg)

**Comment by SaFrMo** [comment]
I'd vote for just adding the polyfill on this one site - that way we know what to do in the future without needing to bloat the responsive-image component unnecessarily. Is this what you ended up doing @drewbaker?

**Comment by drewbaker** [comment]
Yeah it doesn't seem worth supporting this on old browsers. If it keeps coming up, we can talk again about it.
