### ISSUE TITLE
Give hamburger-button a slot

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#76]
I personally would love if the `<hamburger-button>` had a slot, rather than the hardcoded SVG in it. I like how it takes care of the click handling, classes and and style resets, but never need/want the SVG that it's built with. 

This would be sweet!

```
<hamburger-button>
Whatever I want!
</hamburger-button>
```

Maybe if you don't use the slot, it falls back to the SVG it currently has?

**Comment by SaFrMo** [comment]
For sure, good note! We actually already added this as a bullet point in #64, along with a couple other to-dos for this element, so I'm going to close this issue. It's something we should get on soon though!
