### ISSUE TITLE
Responsive-image with no wrapping DIVs

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#8]
Just went over `responsive-image` with Sander. I think it would be great to add some parameters to it to allow for no wrapping DIVs. Maybe like:

```<responsive-image :object="attachmentObject" size="medium" not-wrapped/>```

If it's possible to not have any wrapping, but still have it work with Funkycolor etc, that would be sweet. The reason being, I have a forced 16:9 grid, so I don't need all the wrapping DIVs that `responsive-image` has by default.

**Comment by johndigital** [comment]
@drewbaker I think we can do a little better on this using the background `srcset` properties that you mentioned, but really the wrappers are more for the color support and the smooth fade-in. To get both of those to work well we unfortunately need to put them in separate elements to get transitions to look good. 

We could maybe add some additional logic to have less wrappers in certain scenarios, like if you're not taking advantage of the color feature etc. It would be a decent amount of added code just to get a very minor improvement though, so I'm skeptical that it would be worth it.

For your scenario of the forced 16:9 grid, you can just pass in the `ratio` prop and it will lock all the elements to the number you set.

**Comment by drewbaker** [comment]
OK, well I can always just use the regular image HTML if I want no wrapping.

We should probably add this CSS to the defaults then, because currently the image looks broken:

```
    .image-sizer img {
        top: 0;
        left: 0;
    }
```

In this part: https://github.com/funkhaus/fh-components/blob/master/src/responsive-image/ResponsiveImage.vue#L147-L151

**Comment by johndigital** [comment]
Sounds good, I'll assign to myself to look into this.

**Comment by johndigital** [comment]
Fixed in https://github.com/funkhaus/fh-components/commit/dc9f5cc53248893e5eb7f2f6dfc122428e19c926
