### ISSUE TITLE
Video Stage "auto-offsets" prop not working as expected

### ISSUE THREAD

**Issue by johndigital** [funkhaus/fh-components#87]
In video-stage the `auto-offsets` prop was given a default value of false and a type of `[Boolean, String, Number]`.

The default value of false makes sense, but the type breaks the expected functionality. Since the prop is a Boolean flag we should just enforce a boolean. I would expect to be able to do this to enable that feature:

`<video-stage :src="videoSrc" auto-offsets />`

This doesn't work because strings are valid, so it interprets the value as an empty string which evaluates to false. So to enable the feature you have to explicitly force a boolean like this:

`<video-stage :src="videoSrc" :auto-offsets="true" />`

To fix, we just change the type of that prop to Boolean only.

**Comment by SaFrMo** [comment]
Fixed in 71159bc
