### ISSUE TITLE
Is there a way to get the current index of a slideshow?

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#92]
I have a feeling this is what the sync modifier is for, and it's mentioned in the docs but not explained. 

I want to be able to do this:

```
        <slide-show
            class="slideshow"
            :slides="slides"
        >
            <div class="slide-wrap" slot="slide" slot-scope="args">
        </slide-show>

        <div class="meta">
            The current index of the slideshow is: {{index}}
        </div>
```

Is there a way to get index? Ideally I'm storing index in the `data` of the component too.

**Comment by johndigital** [comment]
You're correct, this is exactly what the sync modifier is for! Here's how you would do it, modified example code:

```Vue
        <slide-show
            class="slideshow"
            :slides="slides"
            :index.sync="index"
        >
            <div class="slide-wrap" slot="slide" slot-scope="args">
        </slide-show>

        <div class="meta">
            The current index of the slideshow is: {{index}}
        </div>
```

Where the variable `index` is initialized in your data method with a value of 0 (or whatever you want the "starting slide" to be.)

With the modifier `index` will be bidirectional, meaning that if you change it the slideshow will switch to that slide _and_ whenever the slide updates on its own the value will be changed as well.

**Comment by johndigital** [comment]
Actually going to leave this issue open so that we can know to update the documentation with an example of this.

**Comment by SaFrMo** [comment]
Updated docs in 196ccac!
