### ISSUE TITLE
Need a slide-show fade transition 

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#94]
Is it possible to get an example of how to make the `slide-show` do a simple fade transition? I guess ideally you'd be able to name any transition and have it use that in someway.

**Comment by SaFrMo** [comment]
There's a method in place for that - you can just use the `force-transition` prop with the name of the animation you have in mind to use that animation. So for the fade transition, you'd do:

```
<slide-show force-transition="fade" ... >
```

Adding to the docs!
