### ISSUE TITLE
Enable video-stage to size by intrinsic ratio

### ISSUE THREAD

**Issue by cyrusdean** [funkhaus/fh-components#96]
Would be handy if `<video-stage>` could tell you the height and width of the iframe.

**Comment by drewbaker** [comment]
When used at top of case studys I like to have the video be 100% by whatever-is-needed high. Like the way FitVids works.

**Comment by drewbaker** [comment]
I could hack this if the video-stage emitted it's high on resize event.

**Comment by johndigital** [comment]
Intrinsic ratio sizing (fitVids style) has been added and documented in b1034f7cef35c871f4a1642dc6e619e540499858 with the `is-responsive` prop. Going to also add in event emitters for height and width.

**Comment by johndigital** [comment]
All set and documented in 5c8e3f8b15f6dd3944029ad42b65f97c8042b38d.

Closing!
